phones_front_end:
    resource: "@PhonesFrontEndBundle/Resources/config/routing.yml"
    prefix:   /

phones_phone:
    resource: "@PhonesPhoneBundle/Resources/config/routing.yml"
    prefix:   /

phones_data_providers_gsm_arena_com:
    resource: "@PhonesDataProvidersGsmArenaComBundle/Resources/config/routing.yml"
    prefix:   /