phones_front_end:
    resource: "@PhonesFrontEndBundle/Resources/config/routing.yml"
    prefix:   /

phones_phone:
    resource: "@PhonesPhoneBundle/Resources/config/routing.yml"
    prefix:   /

# Data providers
phones_data_providers_gsm_arena_com:
    resource: "@PhonesDataProvidersGsmArenaComBundle/Resources/config/routing.yml"
    prefix:   /

# Cost providers
phones_cost_providers_tele_arena_lt:
    resource: "@PhonesCostProvidersTeleArenaLtBundle/Resources/config/routing.yml"
    prefix:   /

phones_cost_providers_gsm_arena_lt:
    resource: "@PhonesCostProvidersGsmArenaLtBundle/Resources/config/routing.yml"
    prefix:   /

phones_cost_providers_mobili_linija:
    resource: "@PhonesCostProvidersMobiliLinijaBundle/Resources/config/routing.yml"
    prefix:   /

phones_stat_providers_dx_o_mark_com:
    resource: "@PhonesStatProvidersDxOMarkComBundle/Resources/config/routing.yml"
    prefix:   /

phones_stat_providers_gsm_arena_com_battery_life:
    resource: "@PhonesStatProvidersGsmArenaComBatteryLifeBundle/Resources/config/routing.yml"
    prefix:   /

phones_stat_providers_gsm_arena_com_basemark_x:
    resource: "@PhonesStatProvidersGsmArenaComBasemarkXBundle/Resources/config/routing.yml"
    prefix:   /

phones_stat_providers_gsm_arena_com_basemark_os_ii:
    resource: "@PhonesStatProvidersGsmArenaComBasemarkOSIIBundle/Resources/config/routing.yml"
    prefix:   /