parameters:
    phones_cost_providers_gsm_arena_lt.providerName: gsmArenaLt
    phones_cost_providers_gsm_arena_lt.domain: http://www.gsmarena.lt/

    phones_cost_providers_gsm_arena_lt.mapping_helper.class: Phones\PhoneBundle\Services\MappingHelper

    phones_cost_providers_gsm_arena_lt.brand_downloader.class: Phones\CostProviders\GsmArenaLtBundle\Service\BrandDownloader
    phones_cost_providers_gsm_arena_lt.main_downloader.class: Phones\CostProviders\GsmArenaLtBundle\Service\MainDownloader

    phones_cost_providers_gsm_arena_lt.main_downloader.phone_brand_link_map:
        Nokia:      http://www.gsmarena.lt/telefonai/nokia
        Sony:       http://www.gsmarena.lt/telefonai/sony-ericsson
        Samsung:    http://www.gsmarena.lt/telefonai/samsung
        LG:         http://www.gsmarena.lt/telefonai/lg
        Apple:      http://www.gsmarena.lt/telefonai/apple
        BlackBerry: http://www.gsmarena.lt/telefonai/blackberry
        HTC:        http://www.gsmarena.lt/telefonai/htc
        Matorola:   http://www.gsmarena.lt/telefonai/motorola
        Huawei:     http://www.gsmarena.lt/telefonai/huawei

services:
    phones_cost_providers_gsm_arena_lt.mapping_helper:
        class: %phones_cost_providers_gsm_arena_lt.mapping_helper.class%
        arguments:
            - %phones_cost_providers_gsm_arena_lt.providerName%
            - @doctrine.orm.entity_manager

    phones_cost_providers_gsm_arena_lt.brand_downloader:
        class: %phones_cost_providers_gsm_arena_lt.brand_downloader.class%
        calls:
            - [setDownloader, [@phones_phone.downloader]]
            - [setTidyService, [@phones_phone.tidy_service]]
            - [setProvider, [%phones_cost_providers_gsm_arena_lt.providerName%]]
            - [setDomain, [%phones_cost_providers_gsm_arena_lt.domain%]]

    phones_cost_providers_gsm_arena_lt.main_downloader:
        class: %phones_cost_providers_gsm_arena_lt.main_downloader.class%
        calls:
            - [setBrandDownloader, [@phones_cost_providers_gsm_arena_lt.brand_downloader]]
            - [setPhoneBrandLinkMap, [%phones_cost_providers_gsm_arena_lt.main_downloader.phone_brand_link_map%]]
            - [setEntityManager, [@doctrine.orm.entity_manager]]
            - [setMappingHelper, [@phones_cost_providers_gsm_arena_lt.mapping_helper]]