parameters:
    phones_cost_providers_mobili_linija.providerName: mobiliLinija
    phones_cost_providers_mobili_linija.domain: http://www.mobili.lt/

    phones_cost_providers_mobili_linija.mapping_helper.class: Phones\PhoneBundle\Services\MappingHelper

    phones_cost_providers_mobili_linija.brand_downloader.class: Phones\CostProviders\MobiliLinijaBundle\Service\BrandDownloader
    phones_cost_providers_mobili_linija.main_downloader.class: Phones\CostProviders\MobiliLinijaBundle\Service\MainDownloader

    phones_cost_providers_mobili_linija.main_downloader.phone_brand_link_map:
#        Nokia:      http://www.mobili.lt/lt/telefonai/nokia.html
#        Samsung:    http://www.mobili.lt/lt/telefonai/samsung.html
#        Sony:       http://www.mobili.lt/lt/telefonai/sony_mobile.html
#        Prestigio:  http://www.mobili.lt/lt/telefonai/prestigio.html
#        LG:         http://www.mobili.lt/lt/telefonai/lg.html
#        HTC:        http://www.mobili.lt/lt/telefonai/htc.html
        Apple:      http://www.mobili.lt/lt/telefonai/apple.html
#        Gsmart:     http://www.mobili.lt/lt/telefonai/gigabyte.html
#        myPhone:    http://www.mobili.lt/lt/telefonai/myphone.html
#        Huawei:     http://www.mobili.lt/lt/telefonai/huawei.html
#        ASUS:       http://www.mobili.lt/lt/telefonai/asus.html
#        BlackBerry: http://www.mobili.lt/lt/telefonai/blackberry.html
#        Matorola:   http://www.mobili.lt/lt/telefonai/motorola.html

services:
    phones_cost_providers_mobili_linija.mapping_helper:
        class: %phones_cost_providers_mobili_linija.mapping_helper.class%
        arguments:
            - %phones_cost_providers_mobili_linija.providerName%
            - @doctrine.orm.entity_manager

    phones_cost_providers_mobili_linija.brand_downloader:
        class: %phones_cost_providers_mobili_linija.brand_downloader.class%
        calls:
            - [setDownloader, [@phones_phone.downloader]]
            - [setTidyService, [@phones_phone.tidy_service]]
            - [setProvider, [%phones_cost_providers_mobili_linija.providerName%]]
            - [setDomain, [%phones_cost_providers_mobili_linija.domain%]]

    phones_cost_providers_mobili_linija.main_downloader:
        class: %phones_cost_providers_mobili_linija.main_downloader.class%
        calls:
            - [setBrandDownloader, [@phones_cost_providers_mobili_linija.brand_downloader]]
            - [setPhoneBrandLinkMap, [%phones_cost_providers_mobili_linija.main_downloader.phone_brand_link_map%]]
            - [setEntityManager, [@doctrine.orm.entity_manager]]
            - [setMappingHelper, [@phones_cost_providers_mobili_linija.mapping_helper]]