Phones\PhoneBundle\Entity\AudioOutput:
    type: entity
    table: stat_audio_output
    id:
        phoneId:
            type: string
            generator:
                strategy: NONE
    fields:
        provider_id:
            type: string
        original_phone_name:
            type: string
            nullable: true
        headphones_power_volts:
            type: float
            nullable: true
        loudspeaker_dB:
            type: float
            nullable: true
        grade:
            type: float
            nullable: true
    oneToOne:
        phone:
            targetEntity: Phone
            inversedBy: audioOutput
            joinColumn:
                name: phoneId
                referencedColumnName: phoneId