Phones\PhoneBundle\Entity\BasemarkOSII:
    type: entity
    table: stat_basemark_os_ii
    repositoryClass: Phones\PhoneBundle\Entity\BasemarkOSIIRepository
    id:
        phoneId:
            type: string
            generator:
                strategy: NONE
    fields:
        provider_id:
            type: string
        original_phone_name:
            type: string
            nullable: true
        basemark_os_ii_rating:
            type: integer
            nullable: true
        grade:
            type: float
            nullable: true
    oneToOne:
        phone:
            targetEntity: Phone
            inversedBy: basemarkOSII
            joinColumn:
                name: phoneId
                referencedColumnName: phoneId