Phones\PhoneBundle\Entity\BatteryLife:
    type: entity
    table: stat_battery_lifes
    id:
        phoneId:
            type: string
            generator:
                strategy: NONE
    fields:
        provider_id:
            type: string
        original_phone_name:
            type: string
            nullable: true
        endurance_rating_min:
            type: integer
            nullable: true
        talk_time_min:
            type: integer
            nullable: true
        web_browsing_min:
            type: integer
            nullable: true
        video_playback_min:
            type: integer
            nullable: true
        grade:
            type: integer
            nullable: true
    oneToOne:
        phone:
            targetEntity: Phone
            inversedBy: batteryLife
            joinColumn:
                name: phoneId
                referencedColumnName: phoneId