Phones\PhoneBundle\Entity\CameraRate:
    type: entity
    table: stat_camera_rates
    id:
        phoneId:
            type: string
            generator:
                strategy: NONE
    fields:
        provider_id:
            type: string
        original_phone_name:
            type: string
            nullable: true
        rate_percent:
            type: integer
            nullable: true
        grade:
            type: float
            nullable: true
    oneToOne:
        phone:
            targetEntity: Phone
            inversedBy: cameraRate
            joinColumn:
                name: phoneId
                referencedColumnName: phoneId