Phones\PhoneBundle\Entity\CameraSpeed:
    type: entity
    table: stat_camera_speed
    id:
        phoneId:
            type: string
            generator:
                strategy: NONE
    fields:
        provider_id:
            type: string
        original_phone_name:
            type: string
            nullable: true
        taking_a_pic_in_sec:
            type: float
            nullable: true
        taking_an_hdr_pic_in_sec:
            type: float
            nullable: true
        camera_speed_score:
            type: integer
            nullable: true
        grade:
            type: float
            nullable: true
    oneToOne:
        phone:
            targetEntity: Phone
            inversedBy: cameraSpeed
            joinColumn:
                name: phoneId
                referencedColumnName: phoneId