Phones\PhoneBundle\Entity\Cost:
    type: entity
    table: cost
    repositoryClass: Phones\PhoneBundle\Entity\CostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        phone_id:
            type: string
            nullable: true
        provider_id:
            type: string
        original_phone_name:
            type: string
            nullable: true
        cost:
            type: float
            nullable: true
        deep_link:
            type: text
            nullable: true
        date_time:
            type: datetime
            nullable: true
    manyToOne:
        phone:
            targetEntity: Phone
            inversedBy: costs
            joinColumn:
                name: phone_id
                referencedColumnName: phoneId