Phones\PhoneBundle\Entity\Cost:
    type: entity
    table: costs
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        phone_id:
            type: string
            nullable: true
        cost:
            type: float
            nullable: true
        provider_id:
            type: string
        deep_link:
            type: text
            nullable: true
