Phones\PhoneBundle\Entity\Provider:
    type: entity
    table: providers
    id:
        id:
            type: string
            generator:
                strategy: NONE
    fields:
        name:
            type: string
            nullable: true
        deep_link:
            type: string
        info:
            type: text
            nullable: true