Phones\PhoneBundle\Entity\Stat:
    type: entity
    table: stats
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        phone_id:
            type: string
            nullable: true
        provider_id:
            type: string
        original_phone_name:
            type: string
            nullable: true
        category:
            type: string
            nullable: true
        meta_key:
            type: string
            nullable: true
        meta_value:
            type: float
            nullable: true
        grade:
            type: integer
            nullable: true
    manyToOne:
        phone:
            targetEntity: Phone
            inversedBy: stats
            joinColumn:
                name: phone_id
                referencedColumnName: phoneId