phones_front_end.homepage:
    pattern:  /
    defaults: { _controller: PhonesFrontEndBundle:Default:index}

phones_front_end.phones:
    pattern:  /phones/{currentPage}
    defaults: { _controller: PhonesFrontEndBundle:Default:phones, currentPage: 1 }
    requirements:
        start:  \d+

phones_front_end.best_phone:
    pattern: /search
    defaults: { _controller: PhonesFrontEndBundle:Default:bestPhoneSearch }

phones_front_end.single_phone:
    pattern:  /phones/phone/{phoneId}
    defaults: { _controller: PhonesFrontEndBundle:Default:singlePhone, phoneId: 0 }

phones_front_end.single_phone_form_search:
    pattern:  /phone_search
    defaults: { _controller: PhonesFrontEndBundle:Default:phoneSearch }

phones_front_end.results:
    pattern:  /results
    defaults: { _controller: PhonesFrontEndBundle:Default:searchResults }

phones_front_end.phones_json:
    pattern:  /phones_json
    defaults: { _controller: PhonesFrontEndBundle:Default:getPhonesJson }