parameters:
    phones_front_end.query_helper.class: Phones\FrontEndBundle\Service\QueryHelper

    #possible filters
    phones_front_end.query_helper.passible_range_names:
        cost:               'COSTS_TABLE'
        weight:             'PHONES_TABLE'
        cpu_freq:           'PHONES_TABLE'
        cpu_cores:          'PHONES_TABLE'
        ram_mb:             'PHONES_TABLE'
        display_size:       'PHONES_TABLE'
        camera_mpx:         'PHONES_TABLE'
        video_p:            'PHONES_TABLE'
        battery_stand_by_h: 'PHONES_TABLE'
        battery_talk_time:  'PHONES_TABLE'

    phones_front_end.query_helper.possible_select_names:
        brand:             'PHONES_TABLE'
        os:                'PHONES_TABLE'
        bluetooth_version: 'PHONES_TABLE'

    phones_front_end.query_helper.possible_like_select_names:
        technology: 'PHONES_TABLE'
        gps:        'PHONES_TABLE'
        wlan:       'PHONES_TABLE'

    phones_front_end.query_helper.possible_checkbox_names:
        external_sd: 'PHONES_TABLE'
        flash:       'PHONES_TABLE'

    phones_front_end.query_helper.joinable_form_tables:
        audio_output: stat_audio_output
        battery_charging_times: stat_battery_charging_times
        battery_lifes: stat_battery_lifes
        camera_rates: stat_camera_rates
        camera_speeds: stat_camera_speed

    phones_front_end.query_helper.db_table_namings:
        PHONES_TABLE: phone
        COSTS_TABLE: cost

    phones_front_end.query_helper.stat_tables_by_providers:
        gsmArenaComBatterylife:   { byColumn: endurance_rating_min, tableName: stat_battery_lifes }
        gsmArenaComBasemarkOSII:  { byColumn: basemark_os_ii_rating, tableName: stat_basemark_os_ii }
        gsmArenaComBasemarkX:     { byColumn: basemark_x_rating, tableName: stat_basemark_x }
        phoneArenaComCameraSpeed: { byColumn: taking_a_pic_in_sec, tableName: stat_camera_speed }

services:
    phones_front_end.query_helper:
        class: %phones_front_end.query_helper.class%
        calls:
            - [setPossibleRangeNames, [%phones_front_end.query_helper.passible_range_names%]]
            - [setPossibleSelectNames, [%phones_front_end.query_helper.possible_select_names%]]
            - [setPossibleLikeSelectNames, [%phones_front_end.query_helper.possible_like_select_names%]]
            - [setPossibleCheckBoxNames, [%phones_front_end.query_helper.possible_checkbox_names%]]
            - [setEntityManager, [@doctrine.orm.entity_manager]]
            - [setDbConnection, [@doctrine.dbal.default_connection]]
            - [setJoinableFormTables, [%phones_front_end.query_helper.joinable_form_tables%]]
            - [setDbTableNamings, [%phones_front_end.query_helper.db_table_namings%]]
            - [setStatTablesByProviders, [%phones_front_end.query_helper.stat_tables_by_providers%]]